In [1]:
import pandas as pd

df = pd.read_csv("/content/employee_productivity_dataset.csv")
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

Now, let's handle the missing values in the `df` DataFrame according to your specifications:
- **Age**: Fill with Median
- **Salary**: Fill with Mean
- **Hours_Worked_Per_Week**: Fill with Median
- **Performance_Score**: Fill with Mean

In [2]:
# Calculate median for 'Age' and 'Hours_Worked_Per_Week'
median_age = df['Age'].median()
median_hours_worked = df['Hours_Worked_Per_Week'].median()

# Calculate mean for 'Salary' and 'Performance_Score'
mean_salary = df['Salary'].mean()
mean_performance_score = df['Performance_Score'].mean()

# Fill missing values
df['Age'].fillna(median_age, inplace=True)
df['Salary'].fillna(mean_salary, inplace=True)
df['Hours_Worked_Per_Week'].fillna(median_hours_worked, inplace=True)
df['Performance_Score'].fillna(mean_performance_score, inplace=True)

print("DataFrame after handling missing values:")
display(df.head())

DataFrame after handling missing values:

/tmp/ipykernel_3089/42655773.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)
/tmp/ipykernel_3089/42655773.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)
/tmp/ipykernel_3089/42655773.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hours_Worked_Per_Week'].fillna(median_hours_worked, inplace=True)
/tmp/ipykernel_3089/42655773.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Score'].fillna(mean_performance_score, inplace=True)

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune

Q2. Label Encoding
Convert these columns into numeric values using Label Encoding:
Gender
Department
Show the updated columns.

In [3]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to 'Gender' column
df['Gender_Encoded'] = le.fit_transform(df['Gender'])

# Apply Label Encoding to 'Department' column
df['Department_Encoded'] = le.fit_transform(df['Department'])

print("DataFrame with 'Gender' and 'Department' columns label encoded:")
display(df[['Gender', 'Gender_Encoded', 'Department', 'Department_Encoded']].head())

DataFrame with 'Gender' and 'Department' columns label encoded:

   Gender  Gender_Encoded Department  Department_Encoded
0    Male               1         IT                   2
1  Female               0         HR                   1
2    Male               1    Finance                   0
3  Female               0         IT                   2
4    Male               1  Marketing                   3

We can check the unique values and their corresponding encoded values for clarity.

In [4]:
print("Gender Mapping:")
for i, item in enumerate(le.classes_):
    print(f"{item} -> {i}")

# Re-initialize LabelEncoder for Department to get correct classes mapping
le_dept = LabelEncoder()
le_dept.fit_transform(df['Department'])

print("\nDepartment Mapping:")
for i, item in enumerate(le_dept.classes_):
    print(f"{item} -> {i}")

Gender Mapping:
Finance -> 0
HR -> 1
IT -> 2
Marketing -> 3

Department Mapping:
Finance -> 0
HR -> 1
IT -> 2
Marketing -> 3

Q3. One-Hot Encoding
Apply One-Hot Encoding on:
Work_Mode
Location
Display the dataset and check how many new columns are created.

One-Hot Encoding is a process that converts categorical variables into a numerical format that can be provided to machine learning algorithms to improve prediction quality. Each category value is converted into a new column and assigned a 1 or 0 (true/false) value.

In [5]:
# Perform One-Hot Encoding on 'Work_Mode' and 'Location'
df_encoded = pd.get_dummies(df, columns=['Work_Mode', 'Location'], drop_first=False)

print("DataFrame after One-Hot Encoding:")
display(df_encoded.head())

DataFrame after One-Hot Encoding:

,Employee_ID,Name,Department,Age,Gender,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Gender_Encoded,Department_Encoded,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune
0,E001,Amit Sharma,IT,25.0,Male,15-01-2021,40.0,5,4.5000,50000.000000,1,2,False,False,True,False,False,False,True
1,E002,Riya Patel,HR,30.0,Female,15-02-2020,38.0,4,4.0000,45000.000000,0,1,True,False,False,False,False,True,False
2,E003,John Mathew,Finance,29.0,Male,10-03-2022,45.0,6,4.3125,60000.000000,1,0,False,True,False,True,False,False,False
3,E004,Sneha Joshi,IT,28.0,Female,22-04-2021,41.0,5,4.2000,52000.000000,0,2,False,False,True,False,True,False,False
4,E005,Arjun Verma,Marketing,35.0,Male,18-05-2020,50.0,7,4.8000,50666.666667,1,3,True,False,False,False,False,False,True

Let's check how many new columns were created by comparing the number of columns before and after encoding.

In [6]:
num_original_columns = df.shape[1]
num_encoded_columns = df_encoded.shape[1]
num_new_columns = num_encoded_columns - num_original_columns

print(f"Original number of columns: {num_original_columns}")
print(f"Number of columns after One-Hot Encoding: {num_encoded_columns}")
print(f"Number of new columns created: {num_new_columns}")

Original number of columns: 14
Number of columns after One-Hot Encoding: 19
Number of new columns created: 5

Q4. Normalization (Min-Max Scaling)
Normalize the following columns:
Salary
Hours_Worked_Per_Week
Use MinMaxScaler and display results.

Min-Max Scaling (Normalization) transforms features by scaling each feature to a given range, typically [0, 1]. This ensures that all features contribute equally to the distance calculations, which is important for many machine learning algorithms. The formula is:

$X_{norm} = (X - X_{min}) / (X_{max} - X_{min})$

In [7]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply Min-Max Scaling to 'Salary' and 'Hours_Worked_Per_Week'
# We will create new columns for the normalized values
df_encoded['Salary_Normalized'] = scaler.fit_transform(df_encoded[['Salary']])
df_encoded['Hours_Worked_Per_Week_Normalized'] = scaler.fit_transform(df_encoded[['Hours_Worked_Per_Week']])

print("DataFrame with normalized 'Salary' and 'Hours_Worked_Per_Week' columns:")
display(df_encoded[['Salary', 'Salary_Normalized', 'Hours_Worked_Per_Week', 'Hours_Worked_Per_Week_Normalized']].head())

DataFrame with normalized 'Salary' and 'Hours_Worked_Per_Week' columns:

,Salary,Salary_Normalized,Hours_Worked_Per_Week,Hours_Worked_Per_Week_Normalized
0,50000.000000,0.347826,40.0,0.285714
1,45000.000000,0.130435,38.0,0.142857
2,60000.000000,0.782609,45.0,0.642857
3,52000.000000,0.434783,41.0,0.357143
4,50666.666667,0.376812,50.0,1.000000

Q5. Standardization (Scaling)
Apply StandardScaler on:
Age Projects_Completed
Display the transformed values.

Standardization (often called Z-score normalization) transforms data such that it has a mean of 0 and a standard deviation of 1. This scaling technique is particularly useful for algorithms that assume a Gaussian distribution of the features, like linear regression, logistic regression, and linear discriminant analysis.

$X_{scaled} = (X - \mu) / \sigma$

In [8]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to 'Age' and 'Projects_Completed'
# We will create new columns for the standardized values
df_encoded['Age_Scaled'] = scaler.fit_transform(df_encoded[['Age']])
df_encoded['Projects_Completed_Scaled'] = scaler.fit_transform(df_encoded[['Projects_Completed']])

print("DataFrame with standardized 'Age' and 'Projects_Completed' columns:")
display(df_encoded[['Age', 'Age_Scaled', 'Projects_Completed', 'Projects_Completed_Scaled']].head())

DataFrame with standardized 'Age' and 'Projects_Completed' columns:

    Age  Age_Scaled  Projects_Completed  Projects_Completed_Scaled
0  25.0   -1.172018                   5                  -0.211604
1  30.0    0.000000                   4                  -0.916949
2  29.0   -0.234404                   6                   0.493742
3  28.0   -0.468807                   5                  -0.211604
4  35.0    1.172018                   7                   1.199088

Q6. Compare Scaling Methods
Apply both:
MinMaxScaler
StandardScaler
On the Salary column.
Show both results side by side.

In [9]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Initialize MinMaxScaler and StandardScaler
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

# Apply MinMaxScaler to the 'Salary' column
df_encoded['Salary_MinMax_Scaled'] = min_max_scaler.fit_transform(df_encoded[['Salary']])

# Apply StandardScaler to the 'Salary' column
df_encoded['Salary_Standard_Scaled'] = standard_scaler.fit_transform(df_encoded[['Salary']])

print("Comparison of original 'Salary' with Min-Max Scaled and Standard Scaled values:")
display(df_encoded[['Salary', 'Salary_MinMax_Scaled', 'Salary_Standard_Scaled']].head())

Comparison of original 'Salary' with Min-Max Scaled and Standard Scaled values:

         Salary  Salary_MinMax_Scaled  Salary_Standard_Scaled
0  50000.000000              0.347826               -0.097451
1  45000.000000              0.130435               -0.828333
2  60000.000000              0.782609                1.364312
3  52000.000000              0.434783                0.194902
4  50666.666667              0.376812                0.000000

Q7. Build Preprocessing Pipeline
Create a pipeline that:
Applies encoding to categorical columns
Applies scaling to numerical columns
Use:
ColumnTransformer
Pipeline

A preprocessing pipeline combines multiple data transformations into a single object, ensuring that the same steps are applied consistently to your data. `ColumnTransformer` allows us to apply different transformations to different subsets of columns, while `Pipeline` chains these transformations together, often culminating in an estimator.

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
import pandas as pd

# Define categorical and numerical features based on previous steps
categorical_features = ['Gender', 'Department', 'Work_Mode', 'Location']
numerical_features_minmax = ['Salary', 'Hours_Worked_Per_Week']
numerical_features_standard = ['Age', 'Projects_Completed', 'Performance_Score']

# Create preprocessing steps using Pipelines for each type of transformation
# Categorical transformer: OneHotEncoder
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Numerical transformer for Min-Max Scaling
numerical_transformer_minmax = Pipeline(steps=[
    ('minmax', MinMaxScaler())
])

# Numerical transformer for Standard Scaling
numerical_transformer_standard = Pipeline(steps=[
    ('standard', StandardScaler())
])

# Create a ColumnTransformer to apply different transformations to different columns
# 'remainder="drop"' will drop columns not specified (like Employee_ID, Name, Join_Date)
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
        ('num_minmax', numerical_transformer_minmax, numerical_features_minmax),
        ('num_standard', numerical_transformer_standard, numerical_features_standard)
    ],
    remainder='drop'
)

# Create the full preprocessing pipeline
# The final step 'preprocessor' is the ColumnTransformer itself, as we only need preprocessing here.
preprocessing_pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit and transform the data using the pipeline
# We use the original `df` which has missing values imputed but no encoding/scaling applied to original columns yet
df_processed_array = preprocessing_pipeline.fit_transform(df)

# Get the names of the transformed features for creating a DataFrame
transformed_feature_names = []

# Get names for one-hot encoded features
cat_feature_names = preprocessing_pipeline.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)
transformed_feature_names.extend(cat_feature_names)

# Get names for Min-Max scaled numerical features
transformed_feature_names.extend(numerical_features_minmax)

# Get names for Standard scaled numerical features
transformed_feature_names.extend(numerical_features_standard)

# Convert the processed array back to a DataFrame for readability
df_transformed = pd.DataFrame(df_processed_array, columns=transformed_feature_names)

print("Shape of the preprocessed data:", df_transformed.shape)
print("\nFirst 5 rows of the transformed DataFrame:")
display(df_transformed.head())

Shape of the preprocessed data: (250, 18)

First 5 rows of the transformed DataFrame:

,Gender_Female,Gender_Male,Department_Finance,Department_HR,Department_IT,Department_Marketing,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune,Salary,Hours_Worked_Per_Week,Age,Projects_Completed,Performance_Score
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.347826,0.285714,-1.172018,-0.211604,0.685224
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.130435,0.142857,0.000000,-0.916949,-1.142041
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.782609,0.642857,-0.234404,0.493742,0.000000
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.434783,0.357143,-0.468807,-0.211604,-0.411135
4,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.376812,1.000000,1.172018,1.199088,1.781584

Q8. Apply Pipeline
Apply the pipeline on the dataset.
Display:
Transformed dataset
Shape of final dataset

In [11]:
print("Shape of the final transformed dataset:", df_transformed.shape)
print("\nFirst 5 rows of the final transformed dataset:")
display(df_transformed.head())

Shape of the final transformed dataset: (250, 18)

First 5 rows of the final transformed dataset:

,Gender_Female,Gender_Male,Department_Finance,Department_HR,Department_IT,Department_Marketing,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune,Salary,Hours_Worked_Per_Week,Age,Projects_Completed,Performance_Score
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.347826,0.285714,-1.172018,-0.211604,0.685224
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.130435,0.142857,0.000000,-0.916949,-1.142041
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.782609,0.642857,-0.234404,0.493742,0.000000
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.434783,0.357143,-0.468807,-0.211604,-0.411135
4,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.376812,1.000000,1.172018,1.199088,1.781584

Q9. Conceptual Question
Why is scaling important in Python?

Scaling data is crucial in many machine learning tasks in Python for several reasons:

Equal Contribution: Many machine learning algorithms (like Support Vector Machines, K-Nearest Neighbors, and neural networks) calculate distances between data points. If features have vastly different scales, the feature with the larger scale will dominate the distance calculation, making the smaller-scaled features almost irrelevant. Scaling ensures all features contribute equally.

Algorithm Performance: Some algorithms converge faster or perform better when features are on a similar scale. For instance, gradient descent-based algorithms (like those used in linear regression or neural networks) benefit from scaling as it helps avoid oscillations and speeds up convergence.

Preventing Domination by Outliers: Features with larger ranges are more susceptible to the influence of outliers. Scaling can help to mitigate this by bringing all features into a comparable range.

Interpretability: While not directly related to model performance, scaling can sometimes make coefficients or feature importances more interpretable, especially when comparing the impact of different features.

Regularization: Techniques like L1 or L2 regularization (Lasso and Ridge regression) penalize large coefficients. If features are not scaled, features with larger magnitudes might be unfairly penalized more heavily.

Q10. Conceptual Question
Why do we convert categorical data into numerical form?

Converting categorical data into numerical form is essential in machine learning for several key reasons:

Algorithm Compatibility: Most machine learning algorithms are designed to work with numerical input. They rely on mathematical operations (like calculating distances, gradients, or weights) that are not directly applicable to text-based or categorical labels. By converting categories to numbers, we make the data compatible with these algorithms.

Order and Magnitude: While some categorical features might have an inherent order (e.g., 'low', 'medium', 'high'), many do not (e.g., 'red', 'green', 'blue'). Numerical representations allow algorithms to understand and utilize this order (in the case of ordinal encoding) or treat each category distinctly without imposing an artificial order (in the case of one-hot encoding).

Feature Engineering: Numerical representations open up possibilities for further feature engineering. For example, with one-hot encoded features, you can create interaction terms.

Avoiding Misinterpretation: If categorical data were used directly as strings, an algorithm might treat them as arbitrary text rather than distinct categories, leading to errors or poor model performance. Even if they are mapped to arbitrary numbers without proper encoding, an algorithm might infer an unintended ordinal relationship (e.g., thinking 'category 2' is 'greater' than 'category 1').